apiVersion: v1
kind: Service
metadata:
  name: phoenix-headless
  namespace: my-app
  labels:
    app: phoenix
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
    - port: 4369
      targetPort: 4369
      protocol: TCP
      name: epmd
  selector:
    app: phoenix
  publishNotReadyAddresses: true
